osx_image: xcode611
language: objective-c

cache:
  - bundler

install:
  - bundle install

script:
  - xctool -scheme ProfileKit -workspace ProfileKit.xcworkspace
  - xctool test -scheme ProfileKit -workspace ProfileKit.xcworkspace